# Generated by Django 3.0 on 2019-12-02 16:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_agree', models.IntegerField(default=0)),
                ('votes_disagree', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2019, 12, 2, 16, 28, 15, 46023))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2019, 12, 2, 16, 28, 15, 46044))),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='jalas_app.Meeting')),
            ],
        ),
    ]
