# Generated by Django 3.0 on 2019-12-03 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(choices=[(0, 'init'), (1, 'pending'), (2, 'finalized')], default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 12, 19, 45, 676319)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 12, 19, 45, 676279)),
        ),
    ]
