# Generated by Django 2.2.7 on 2019-12-13 15:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jalas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='jalas_app.Person'),
        ),
        migrations.AlterField(
            model_name='attendees',
            name='polls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='jalas_app.Poll'),
        ),
        migrations.AlterField(
            model_name='option',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 15, 10, 8, 150575)),
        ),
        migrations.AlterField(
            model_name='option',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 15, 10, 8, 150553)),
        ),
    ]
