# Generated by Django 3.0 on 2019-12-03 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalas_app', '0002_auto_20191203_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(choices=[(0, 'init'), (1, 'pending'), (2, 'finalized'), (3, 'canceled')]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 14, 30, 59, 164733)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 14, 30, 59, 164710)),
        ),
    ]
