# Generated by Django 3.0 on 2019-12-13 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalas_app', '0003_auto_20191203_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(choices=[(0, 'init'), (1, 'pending'), (2, 'finalized'), (3, 'canceled'), (4, 'errored')]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 11, 43, 44, 837337)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 11, 43, 44, 837316)),
        ),
    ]
