# Generated by Django 3.0 on 2019-12-13 14:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jalas_app', '0004_auto_20191213_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2019, 12, 13, 14, 7, 13, 357836))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2019, 12, 13, 14, 7, 13, 357856))),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(default='Asgar', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='status',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='votes_agree',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='votes_disagree',
        ),
        migrations.AddField(
            model_name='poll',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='status',
            field=models.IntegerField(choices=[(0, 'init'), (1, 'pending'), (2, 'finalized'), (3, 'canceled'), (4, 'errored')], default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_set', to='jalas_app.Option')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options_set', to='jalas_app.Poll'),
        ),
    ]
